### ISSUE TITLE
Requirements install error: 'sklearn' deprecated, use 'scikit-learn'

### ISSUE THREAD

**Issue by glossyio** [jacobmarks/active-learning-plugin#1]
# Overview
I am trying to install this plugin and the requirements, and the requirements installation errors out due to 'sklearn' being deprecated.  

What would be the best way to resolve this for this package to work?  And, could I request an update to this package to avoid the error?  

I am user interested in using this package.  Thank you!

# Desired behavior
Install the plugin and requirements without error, using the 'scikit-learn' package instead of 'sklearn'.

# To replicate error

Installed the plugin with `fiftyone plugins download https://github.com/jacobmarks/active-learning-plugin`
And ran install requirements with `fiftyone plugins requirements @jacobmarks/active_learning --install`

During requirements installation, I hit this error:

```
Collecting sklearn
  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
Traceback (most recent call last):
  File "/usr/local/bin/fiftyone", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/fiftyone/core/cli.py", line 4267, in main
    args.execute(args)
  File "/usr/local/lib/python3.10/dist-packages/fiftyone/core/cli.py", line 4250, in <lambda>
    parser.set_defaults(execute=lambda args: command.execute(parser, args))
  File "/usr/local/lib/python3.10/dist-packages/fiftyone/core/cli.py", line 3359, in execute
    fop.install_plugin_requirements(name, error_level=error_level)
  File "/usr/local/lib/python3.10/dist-packages/fiftyone/plugins/core.py", line 309, in install_plugin_requirements
    fou.install_requirements(req_path, error_level=error_level)
  File "/usr/local/lib/python3.10/dist-packages/fiftyone/core/utils.py", line 476, in install_requirements
    install_package(req_str, error_level=error_level)
  File "/usr/local/lib/python3.10/dist-packages/fiftyone/core/utils.py", line 377, in install_package
    return etau.install_package(
  File "/usr/local/lib/python3.10/dist-packages/eta/core/utils.py", line 662, in install_package
    handle_error(PackageError(error_msg), error_level)
  File "/usr/local/lib/python3.10/dist-packages/eta/core/utils.py", line 1004, in handle_error
    raise error
eta.core.utils.PackageError: Failed to install package 'sklearn'

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python -m pip install --upgrade pip
```

**Comment by jacobmarks** [comment]
Hey @glossyio, thanks so much for the heads up, and apologies for the delay!

The issue has been fixed as of this morning :)

https://github.com/jacobmarks/active-learning-plugin/commit/266c104b0a5b5945092fcb1fb1337d3af432658f
